name: Build Box64 Android GLIBC
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ptitSeb/box64
          ref: v0.4.0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DARM64=1 \
            -DARM_DYNAREC=ON \
            -DBAD_SIGNAL=ON \
            -DANDROID=1 \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -G Ninja
          ninja -j$(nproc)

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: box64-android-glibc
          path: build/box64
          retention-days: 90